# PostgreSQL Database Configurations
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/blogdatabase
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true  # Affiche les requêtes SQL dans les logs
        format_sql: true  # Formate les requêtes SQL pour une meilleure lisibilité

# Logging Configurations
logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG  # Afficher les requêtes SQL
    org.hibernate.type.descriptor.sql: trace  # Afficher les détails des valeurs des paramètres bindés

# Autres configurations...
