spring:
  # Spring Security Configuration
  security:
    user:
      name: @Khalid
      password: @passwordAdmin
      roles: USER

  # PostgreSQL Database Configurations
  datasource:
    url: jdbc:postgresql://localhost:5432/blogdatabase
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true  # Active l'affichage des requêtes SQL dans les logs
        format_sql: true  # Formate les requêtes SQL pour une meilleure lisibilité

# Logging Configurations
logging:
  level:
    root: INFO
    org:
      hibernate:
        SQL: DEBUG  # Affiche les requêtes SQL
        type:
          descriptor:
            sql: trace  # Affiche les détails des valeurs des paramètres bindés et les résultats des requêtes
      springframework:
        security: DEBUG  # Debug level for Spring Security

# Autres configurations...
server:
  port: 8082